DROP TABLE IF EXISTS `fact_account_daily_metrics`;

CREATE TABLE `fact_account_daily_metrics` (
  `run_date` datetime NOT NULL,
  `account_id` varchar(32) COLLATE utf8_bin NOT NULL,
  `external_account_id` varchar(32) NOT NULL,
  `account_type` smallint(6) DEFAULT NULL,
  `state_id` char(2) NOT NULL,
  `district_name` varchar(255),
  `school_name` varchar(255),
  `account_manager_email` varchar(100) DEFAULT NULL,
  `current_academic_year` char(13) DEFAULT NULL,
  `current_academic_year_end_date_id` date DEFAULT NULL,
  `math_contract_number` varchar(255) DEFAULT NULL,
  `math_expiration_date_id` date DEFAULT NULL,
  `math_num_enrolled_students` int(11) DEFAULT NULL,
  `math_diagnostic_seats` int(11) DEFAULT NULL,
  `math_diagnostic_seats_consumed` int(11) DEFAULT NULL,
  `math_diagnostic_num_students_with_one_completion` int(11) DEFAULT NULL,
  `math_diagnostic_num_students_with_two_completions` int(11) DEFAULT NULL,
  `math_diagnostic_num_students_with_three_completions` int(11) DEFAULT NULL,
  `math_diagnostic_window_earliest_start_date_id` date DEFAULT NULL,
  `math_diagnostic_window_target_completion_date_id` date DEFAULT NULL,
  `math_diagnostic_window_num_students_with_completion` int(11) DEFAULT NULL,
  `math_diagnostic_window_num_students_with_red_rush_flag` int(11) DEFAULT NULL,
  `math_diagnostic_window_num_students_with_yellow_rush_flag` int(11) DEFAULT NULL,
  `math_instruction_purchased` bool,
  `math_instruction_seats` int(11) DEFAULT NULL,
  `math_instruction_seats_consumed` int(11) DEFAULT NULL,
  `math_instruction_num_students_active_prior_4weeks` int(11) DEFAULT NULL,
  `math_instruction_num_students_meeting_45` int(11) DEFAULT NULL,
  `math_instruction_num_students_meeting_30` int(11) DEFAULT NULL,
  `math_instruction_average_time_on_task` int(11) DEFAULT NULL,
  `math_instruction_num_students_meeting_45_4weeks` int(11) DEFAULT NULL,
  `math_instruction_num_students_meeting_30_4weeks` int(11) DEFAULT NULL,
  `math_instruction_average_time_on_task_4weeks` int(11) DEFAULT NULL,
  `ela_contract_number` varchar(255) DEFAULT NULL,
  `ela_expiration_date_id` date DEFAULT NULL,
  `ela_num_enrolled_students` int(11) DEFAULT NULL,
  `ela_diagnostic_seats` int(11) DEFAULT NULL,
  `ela_diagnostic_seats_consumed` int(11) DEFAULT NULL,
  `ela_diagnostic_num_students_with_one_completion` int(11) DEFAULT NULL,
  `ela_diagnostic_num_students_with_two_completions` int(11) DEFAULT NULL,
  `ela_diagnostic_num_students_with_three_completions` int(11) DEFAULT NULL,
  `ela_diagnostic_window_earliest_start_date_id` date DEFAULT NULL,
  `ela_diagnostic_window_target_completion_date_id` date DEFAULT NULL,
  `ela_diagnostic_window_num_students_with_completion` int(11) DEFAULT NULL,
  `ela_diagnostic_window_num_students_with_red_rush_flag` int(11) DEFAULT NULL,
  `ela_diagnostic_window_num_students_with_yellow_rush_flag` int(11) DEFAULT NULL,
  `ela_instruction_purchased` bool,
  `ela_instruction_seats` int(11) DEFAULT NULL,
  `ela_instruction_seats_consumed` int(11) DEFAULT NULL,
  `ela_instruction_num_students_active_prior_4weeks` int(11) DEFAULT NULL,
  `ela_instruction_num_students_meeting_45` int(11) DEFAULT NULL,
  `ela_instruction_num_students_meeting_30` int(11) DEFAULT NULL,
  `ela_instruction_average_time_on_task_last_week` int(11) DEFAULT NULL,
  `ela_instruction_num_students_meeting_45_4weeks` int(11) DEFAULT NULL,
  `ela_instruction_num_students_meeting_30_4weeks` int(11) DEFAULT NULL,
  `ela_instruction_average_time_on_task_4weeks` int(11) DEFAULT NULL,
  PRIMARY KEY (`run_date`,`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
